### ISSUE TITLE
Possible to grab video?

### ISSUE THREAD

**Issue by awe-is** [Yetangitu/Spodcast#2]
@Yetangitu firstly, _**thank you so much**_ for Spodcast! Secondly, I'm not a developer and so I'm unfamiliar with the etiquette of posting here (please delete if this is out of place). 

Is it possible to grab the video feed alongside the audio? I appreciate that this is probably outside of the project scope. If it is possible then perhaps someone might fork at some point. I'd love to delete Spotify altogether, but I like having Picture-in-Picture while I work.

**Comment by Yetangitu** [comment]
I had a look at video after I - somewhat prematurely - answered to a similar request at HN that it would be rather easy. Well, it isn't. _Spodcast_ rides on the shoulders of _librespot-python_ which is a python port of _librespot_. The former currently does not support video (yet), I have no idea whether this is planned. Even if/when it is supported it would have to deal with DRM (_Widevine_) which is a pain in the ass and something better avoided. So, for now, now video. I never even thought of including it myself since I listen to netcasts while I work (outside, on the farm and in the forest etc) where my eyes are needed elsewhere.
